export interface Trail {
  id: string;
  name: string;
  difficulty: "Easy" | "Easy-Moderate" | "Moderate" | "Moderate-Hard" | "Hard" | "Expert";
  distance: string;
  duration: string;
  elevation: string;
  description: string;
  tags: string[];
  image: string;
  imageIsReal: boolean;
  region: string;
  tips: string[];
  bestFor: string[];
}

export interface Beach {
  id: string;
  name: string;
  crowdLevel: number;
  crowdLabel: string;
  description: string;
  activities: string[];
  region: string;
  image: string;
  imageIsReal: boolean;
  facilities: { name: string; available: boolean }[];
  bestSeason: string;
  surf?: { waveSize: string; skillLevel: string; bestMonths: string };
  tips: string[];
}

export interface SurfSpot {
  id: string;
  name: string;
  waveHeight: number;
  waveLabel: string;
  skillLevel: "Beginner" | "Intermediate" | "Intermediate-Expert" | "Expert";
  description: string;
  bestSeason: string;
  season: "summer" | "winter" | "year-round";
}

export interface Region {
  id: string;
  name: string;
  tagline: string;
  description: string;
  image: string;
  trails: { name: string; difficulty: string; distance: string; description: string }[];
  beaches: { name: string; description: string }[];
  keySeason: string;
}

// ─── Regions ───────────────────────────────────────────

export const regions: Region[] = [
  {
    id: "honolulu",
    name: "Honolulu / Waikiki",
    tagline: "Urban & Historic",
    description: "The heart of Oahu — city energy, iconic landmarks, and beginner-friendly surf.",
    image: "/images/real/8_Must_things_to_do_in_Honolulu_Conquer.jpg",
    trails: [
      { name: "Diamond Head Summit", difficulty: "Moderate", distance: "1.6 mi", description: "Climb inside a 300,000-year-old volcanic tuff cone for panoramic Waikiki views." },
      { name: "Koko Head Crater", difficulty: "Hard", distance: "1.8 mi", description: "1,048 railroad ties straight up — the ultimate island workout." },
      { name: "Manoa Falls", difficulty: "Easy", distance: "1.6 mi", description: "Bamboo groves and a 150-foot waterfall in a prehistoric rainforest." },
      { name: "Makapuu Lighthouse", difficulty: "Easy", distance: "2 mi", description: "Paved coastal trail with winter whale watching." },
      { name: "Hanauma Bay Ridge", difficulty: "Moderate", distance: "3.5 mi", description: "Best aerial views of Hanauma Bay with Koko Head as backdrop." },
      { name: "Makiki Valley Loop", difficulty: "Moderate", distance: "3.2 mi", description: "Lush forest loop with walls of green and ferns." },
      { name: "Kuliouou Ridge", difficulty: "Moderate", distance: "4.7 mi", description: "Ironwood pines to narrow ridgeline above Waimanalo Bay." },
      { name: "Ka'au Crater", difficulty: "Hard", distance: "5 mi", description: "Waterfalls, ridgeline, and crater rim with rope sections." },
      { name: "Manoa Cliff Trail", difficulty: "Easy-Moderate", distance: "4 mi", description: "Bamboo hallways in the lush Manoa Valley rainforest." },
      { name: "Ualaka'a Trail", difficulty: "Easy", distance: "1 mi", description: "Peaceful forest loop with panoramic Honolulu views." },
    ],
    beaches: [
      { name: "Waikiki Beach", description: "The heart of Hawaii — calm water, surf lessons, and endless energy." },
      { name: "Hanauma Bay", description: "Protected marine preserve with world-class snorkeling." },
      { name: "Ala Moana Beach Park", description: "Calm lagoon swimming near Waikiki — locals' favorite." },
      { name: "Sandy Beach", description: "Famous bodyboarding beach with powerful shore break." },
      { name: "Halona Beach Cove", description: "Secluded cove below the Halona Blowhole lookout." },
    ],
    keySeason: "Summer: Calm South Shore swimming & beginner surf. Winter: Small South Shore waves.",
  },
  {
    id: "north-shore",
    name: "North Shore",
    tagline: "Big Wave Country",
    description: "World-class surfing, laid-back country vibes, and legendary winter waves.",
    image: "/images/real/7_Spot_Check_Sunset_Beach_T_C_Surf.jpg",
    trails: [
      { name: "Ehukai Pillbox (Peace Hike)", difficulty: "Moderate", distance: "2.5 mi", description: "Ridgeline views of Pipeline, Sunset Beach, and Keiki's." },
      { name: "Waimea Valley", difficulty: "Easy", distance: "1.5 mi", description: "Botanical garden stroll ending at a swimmable waterfall." },
      { name: "Kaunala Trail", difficulty: "Hard", distance: "6 mi", description: "Hidden gem with deep forest and ridge sections." },
      { name: "Kealia Trail", difficulty: "Moderate", distance: "6.5 mi", description: "Switchbacks with wide-open mountain and coastal views." },
      { name: "Sunset Pillbox", difficulty: "Easy-Moderate", distance: "1.5 mi", description: "Colorful bunkers with stunning North Shore sunset views." },
    ],
    beaches: [
      { name: "Sunset Beach", description: "Legendary surf spot with waves to 20ft and golden sunsets." },
      { name: "Waimea Bay", description: "Big-wave surfing birthplace with summer cliff jumping." },
      { name: "Shark's Cove", description: "Marine reserve with crystal-clear summer snorkeling." },
      { name: "Ehukai Beach (Pipeline)", description: "World-famous Banzai Pipeline — most photographed wave." },
      { name: "Laniakea (Turtle Beach)", description: "Gentle reef break with Hawaiian green sea turtles on shore." },
      { name: "Malaekahana Beach", description: "Quiet beach between Laie and Kahuku with camping." },
      { name: "Turtle Bay", description: "Resort beach with calm swimming and nearby hiking trails." },
    ],
    keySeason: "Winter: Massive surf (15-50ft) — experts only. Summer: Calm swimming & snorkeling.",
  },
  {
    id: "windward",
    name: "Windward (East)",
    tagline: "Turquoise Coast",
    description: "Turquoise waters, mountain backdrops, kayaking paradise, and pristine beaches.",
    image: "/images/real/1_Aerial_view_of_a_Kailua_beach_on.jpg",
    trails: [
      { name: "Lanikai Pillbox", difficulty: "Easy-Moderate", distance: "1.8 mi", description: "Sunrise hike to WWII pillboxes above turquoise water." },
      { name: "Olomana (Three Peaks)", difficulty: "Hard", distance: "5 mi", description: "Three dramatic peaks with steep drop-offs — not for beginners." },
      { name: "Maunawili Falls", difficulty: "Moderate", distance: "3 mi", description: "Jungle trek through streams to a hidden waterfall." },
      { name: "Crouching Lion", difficulty: "Moderate", distance: "2 mi", description: "Short steep hike with breathtaking views of Kahana Bay." },
      { name: "Pride Rock to Pu'u Ohulehule", difficulty: "Hard", distance: "5.6 mi", description: "Technical ridge hike with incredible Kualoa Mountain views." },
      { name: "Pu'u Piei Makai", difficulty: "Hard", distance: "2.5 mi", description: "Steep climb with ropes over Kahana Bay." },
      { name: "Judd Trail", difficulty: "Easy", distance: "1.2 mi", description: "Natural water slides, rope swings, and bamboo forest." },
      { name: "Friendship Gardens", difficulty: "Easy", distance: "0.7 mi", description: "Hidden gem with Ko'olau Mountain and Kaneohe Bay views." },
      { name: "Hauula Loop", difficulty: "Moderate", distance: "4.4 mi", description: "Peaceful forest trail with panoramic coastline views." },
    ],
    beaches: [
      { name: "Lanikai Beach", description: "Powdery white sand and turquoise water — one of the world's best." },
      { name: "Kailua Beach", description: "2.5 miles of family-friendly shoreline with kayaking." },
      { name: "Waimanalo Beach", description: "Miles of quiet shoreline with natural shade." },
      { name: "Bellows Beach", description: "Wide sandy beach popular with locals and military families." },
      { name: "Chinaman's Hat (Mokolii)", description: "Kayak to a distinctive island in Kaneohe Bay." },
      { name: "Makapuu Beach", description: "Dramatic black cliffs with powerful bodyboarding waves." },
      { name: "Kahana Bay", description: "Secluded bay with shade trees, picnic tables, and camping." },
    ],
    keySeason: "Year-round: Calm swimming & kayaking. Trade winds pick up in afternoons.",
  },
  {
    id: "leeward",
    name: "Leeward (West)",
    tagline: "Sunny West Side",
    description: "Dry and sunny, resort lifestyle, less touristy, with hot temperatures.",
    image: "/images/real/3_Hiking_the_Pu_u_O_Hulu_Trail_Pink.jpg",
    trails: [
      { name: "Pink Pillbox (Maili)", difficulty: "Moderate", distance: "1.6 mi", description: "West Side ridgeline to a pink bunker with fiery sunset views." },
      { name: "Kaena Point (West)", difficulty: "Easy-Moderate", distance: "5 mi", description: "Flat coastal trail to wildlife refuge with monk seals." },
    ],
    beaches: [
      { name: "Ko Olina Lagoons", description: "Four calm man-made lagoons with pool-like water." },
      { name: "Electric Beach (Kahe Point)", description: "Freshwater springs attract sea turtles and reef sharks." },
      { name: "Yokohama Bay", description: "Remote, pristine beach at the end of the road on the West Side." },
      { name: "Maili Beach", description: "Local beach park with swimming and picnicking." },
      { name: "Nanakuli Beach", description: "Quiet beach with fewer crowds and warm waters." },
      { name: "Pokai Bay", description: "Protected bay with small, gentle waves — beginner friendly." },
    ],
    keySeason: "Year-round: Dry, sunny, and warm. Best snorkeling in summer.",
  },
  {
    id: "central",
    name: "Central Oahu",
    tagline: "Valleys & Forests",
    description: "Lush valleys, dense forests, waterfalls, and residential areas.",
    image: "/images/real/4_Hiking_the_Aiea_Loop_Trail_on_O_ahu.jpg",
    trails: [
      { name: "Aiea Loop", difficulty: "Moderate", distance: "4.8 mi", description: "Forest bath through eucalyptus and a WWII B-24 bomber wreck." },
      { name: "Wiliwilinui Ridge", difficulty: "Moderate-Hard", distance: "5 mi", description: "Wide ridge trail to 360-degree windward valley views." },
      { name: "Wailupe Loop", difficulty: "Hard", distance: "5.2 mi", description: "Challenging loop with 800m elevation gain on the Koolau Summit Trail." },
      { name: "Pali Notches", difficulty: "Hard", distance: "0.75 mi", description: "Dangerous ridge scramble with historic notches carved by Kamehameha's warriors." },
      { name: "Nuuanu Trail to Pali Lookout", difficulty: "Moderate", distance: "6.2 mi", description: "Stream crossings and bamboo forest to the Pali Lookout." },
      { name: "Pu'u Pia Trail", difficulty: "Easy-Moderate", distance: "3.6 mi", description: "Lush forest hike with Ko'olau Mountain range views." },
      { name: "Lulumahu Falls", difficulty: "Moderate", distance: "2-3 mi", description: "Stream crossings and bamboo forest to a 50-foot waterfall." },
      { name: "Laie Falls", difficulty: "Moderate-Hard", distance: "7 mi", description: "Long forest hike to a waterfall deep in the jungle." },
    ],
    beaches: [],
    keySeason: "Year-round hiking. Lush and green. Can be muddy after rain.",
  },
];

// ─── All Trails (35+) ──────────────────────────────────

export const trails: Trail[] = [
  {
    id: "diamond-head",
    name: "Diamond Head Summit",
    difficulty: "Moderate",
    distance: "1.6 mi",
    duration: "1-2 hrs",
    elevation: "560 ft",
    description: "The most iconic hike in Hawaii. Climb through a WWII-era tunnel and military bunkers for a 360-degree view of Waikiki, the coastline, and the Ko'olau Mountains.",
    tags: ["Iconic", "Viewpoint", "Tunnel", "Reservations Required"],
    image: "/images/real/5_Hiking_the_Diamond_Head_Trail_L_ahi.jpg",
    imageIsReal: true,
    region: "Honolulu",
    tips: ["Reservations REQUIRED — book 30+ days ahead at DLNR website", "$5 entry fee + $10 parking (credit card only)", "Go before 7 AM to beat heat and crowds"],
    bestFor: ["First-time visitors", "Sunrise seekers", "Photography"],
  },
  {
    id: "lanikai-pillbox",
    name: "Lanikai Pillbox (Kaiwa Ridge)",
    difficulty: "Easy-Moderate",
    distance: "1.8 mi",
    duration: "1.5 hrs",
    elevation: "600 ft",
    description: "A short, steep climb to two WWII pillboxes overlooking Lanikai Beach and the Mokulua Islands. The colors at sunrise are unreal.",
    tags: ["Sunrise", "Ridge", "Photography", "Family Friendly"],
    image: "/images/real/4_How_to_Watch_Sunrise_at_the_Lanikai.jpg",
    imageIsReal: true,
    region: "Windward",
    tips: ["Get there by 5:30 AM for sunrise", "Parking is tight on residential streets — be respectful", "Trail has loose rock near the top"],
    bestFor: ["Sunrise lovers", "Instagram photographers", "Quick rewarding hike"],
  },
  {
    id: "koko-head",
    name: "Koko Head Crater Trail",
    difficulty: "Hard",
    distance: "1.8 mi",
    duration: "1.5-2 hrs",
    elevation: "1,048 ft",
    description: "Not a hike — it's a stair climb. 1,048 old railway ties straight up the side of Koko Crater. Brutal, but the views are among the best on the island.",
    tags: ["Workout", "Challenge", "Summit", "Stairs"],
    image: "/images/real/7_How_to_Hike_Oahu_s_Koko_Head_Stair.jpg",
    imageIsReal: true,
    region: "Honolulu",
    tips: ["Bring at least 1 liter of water — no shade", "Start before sunrise for cooler temps", "There's a bypass around the bridge gap section"],
    bestFor: ["Fitness enthusiasts", "Challenge seekers", "View lovers"],
  },
  {
    id: "manoa-falls",
    name: "Manoa Falls Trail",
    difficulty: "Easy",
    distance: "1.6 mi",
    duration: "1-2 hrs",
    elevation: "800 ft",
    description: "A lush, shaded rainforest walk that ends at a 150-foot waterfall. Filming location for Jurassic Park and Lost. The trail can be muddy year-round.",
    tags: ["Waterfall", "Rainforest", "Family", "Movie Location"],
    image: "/images/real/10_Hiking_Manoa_Falls_Trail_In_Honolulu.jpg",
    imageIsReal: true,
    region: "Honolulu",
    tips: ["Wear shoes with grip — not slippers", "$7 parking at the trailhead lot", "Don't swim at the falls — leptospirosis risk"],
    bestFor: ["Families", "Nature lovers", "Jungle experience"],
  },
  {
    id: "makapuu-lighthouse",
    name: "Makapuu Point Lighthouse",
    difficulty: "Easy",
    distance: "2 mi",
    duration: "1-1.5 hrs",
    elevation: "500 ft",
    description: "Fully paved coastal trail with sweeping views of the windward coast and Rabbit Island. During whale season (Nov-Apr), spot humpback whales breaching offshore.",
    tags: ["Coastal", "Paved", "Family", "Whale Watch"],
    image: "/images/real/1_Hiking_the_Makapuu_Lighthouse_Trai.jpg",
    imageIsReal: true,
    region: "Windward",
    tips: ["No shade — bring sunscreen and a hat", "Bring binoculars for whale watching", "Stroller-friendly and accessible"],
    bestFor: ["Families with strollers", "Whale watchers", "Coastal scenery"],
  },
  {
    id: "ehukai-pillbox",
    name: "Ehukai Pillbox (Peace Hike)",
    difficulty: "Moderate",
    distance: "2.5 mi",
    duration: "1-1.5 hrs",
    elevation: "740 ft",
    description: "One of the best short trails for sunset views of the North Shore beaches. Watch sets of waves forming before barreling at Pipeline, Sunset Beach, and Keiki's.",
    tags: ["Ridge", "Surf View", "North Shore", "Sunset"],
    image: "/images/real/8_Ehukai_Pillbox_Hike_The_Best_Hike.jpg",
    imageIsReal: true,
    region: "North Shore",
    tips: ["Arrive before 7 AM — parking fills fast at Ehukai Beach Park", "Wear shoes with good grip", "One of the best sunset spots on the island"],
    bestFor: ["Surf watchers", "Sunset seekers", "North Shore visitors"],
  },
  {
    id: "kaena-point",
    name: "Kaena Point Trail",
    difficulty: "Easy-Moderate",
    distance: "5 mi",
    duration: "2-3 hrs",
    elevation: "Minimal",
    description: "Flat coastal trail to a wildlife refuge at Oahu's westernmost tip. Spot Hawaiian monk seals sunbathing, Laysan albatrosses nesting, and seabirds.",
    tags: ["Wildlife", "Coastal", "Flat", "Dog Friendly"],
    image: "/images/real/5_Hawaiian_monk_seal_makes_epic_journey.jpg",
    imageIsReal: true,
    region: "Leeward / North Shore",
    tips: ["No shade — start early and bring extra water", "Sun reflects off white sand — feels 10 degrees hotter", "Best in winter for massive surf views"],
    bestFor: ["Wildlife enthusiasts", "Dog owners", "Coastal walkers"],
  },
  {
    id: "waimea-valley",
    name: "Waimea Valley Trail",
    difficulty: "Easy",
    distance: "1.5 mi",
    duration: "1-2 hrs",
    elevation: "Minimal",
    description: "Botanical garden stroll through a sacred Hawaiian valley with world-class plant collections, historical sites, and a swimmable 45-foot waterfall with lifeguards.",
    tags: ["Waterfall", "Family", "Cultural", "Swimming"],
    image: "/images/real/7_Waimea_Valley_Hike_Swim_Oahu_2026.jpg",
    imageIsReal: true,
    region: "North Shore",
    tips: ["Go when the park opens at 9 AM to beat crowds", "Entrance fee supports valley preservation", "Life jackets provided — swimming allowed here"],
    bestFor: ["Families with kids", "Botanical enthusiasts", "Cultural history"],
  },
  {
    id: "wiliwilinui-ridge",
    name: "Wiliwilinui Ridge Trail",
    difficulty: "Moderate-Hard",
    distance: "5 mi",
    duration: "3-4 hrs",
    elevation: "1,640 ft",
    description: "Wide, well-maintained ridge trail through clouds to a 360-degree summit view of windward valleys, Waikiki, and the turquoise east coast.",
    tags: ["Ridge", "Summit", "360 View", "Stairs"],
    image: "/images/real/1_Hiking_to_the_Scenic_Summit_of_Oahu.jpg",
    imageIsReal: true,
    region: "Honolulu",
    tips: ["Trailhead in gated community — show ID for parking pass", "Limited passes daily — go early", "Bring a windbreaker — windy and chilly at summit"],
    bestFor: ["Adventure seekers", "360-degree views", "Cloud forest experience"],
  },
  {
    id: "kuliouou-ridge",
    name: "Kuliouou Ridge Trail",
    difficulty: "Moderate",
    distance: "4.7 mi",
    duration: "2.5-4 hrs",
    elevation: "1,650 ft",
    description: "From dry forest through towering ironwood pines to a narrow ridgeline above Waimanalo Bay. A favorite sunrise hike with views from Lanikai to Diamond Head.",
    tags: ["Ridge", "Sunrise", "Varied Terrain", "Stairs"],
    image: "/images/real/6_7_Best_Oahu_Sunrise_Hikes_For_You.jpg",
    imageIsReal: true,
    region: "Honolulu",
    tips: ["Go early morning for shade in the pine forest", "Final section has several hundred stairs", "Views of Waimanalo Beach and Rabbit Island"],
    bestFor: ["Terrain variety lovers", "Sunrise hikers", "Ridge walkers"],
  },
  {
    id: "pink-pillbox",
    name: "Pink Pillbox (Pu'u O Hulu)",
    difficulty: "Moderate",
    distance: "1.6 mi",
    duration: "1-2 hrs",
    elevation: "690 ft",
    description: "West Side ridgeline hike to a breast-cancer-awareness pink bunker with fiery sunset views over the Waianae Coast. Five pillboxes along the ridge.",
    tags: ["Sunset", "Photography", "West Side", "Pillboxes"],
    image: "/images/real/7_The_5_Most_Popular_Pillbox_Hikes.jpg",
    imageIsReal: true,
    region: "Leeward",
    tips: ["Best at sunset — orange and purple sky shows", "West Side is hotter than Honolulu — hydrate often", "The pink pillbox is the 4th — don't stop early"],
    bestFor: ["Sunset chasers", "Photographers", "West Side explorers"],
  },
  {
    id: "aiea-loop",
    name: "Aiea Loop Trail",
    difficulty: "Moderate",
    distance: "4.8 mi",
    duration: "2-3 hrs",
    elevation: "900 ft",
    description: "Forest bath through Norfolk Island pines and lemon eucalyptus along Halawa Valley. Discover the remains of a WWII B-24 bomber that crashed in 1944.",
    tags: ["Forest", "Historical", "Loop", "Bomber Wreck"],
    image: "/images/real/4_Hiking_the_Aiea_Loop_Trail_on_O_ahu.jpg",
    imageIsReal: true,
    region: "Central",
    tips: ["Great rainy day hike — canopy provides cover", "Wear shoes that can get muddy and wet", "Stream crossing at the end of the trail"],
    bestFor: ["Forest bathers", "History buffs", "All-season hikers"],
  },
  {
    id: "koko-crater-rim",
    name: "Koko Crater Rim Trail",
    difficulty: "Hard",
    distance: "2.5 mi",
    duration: "1.5-2 hrs",
    elevation: "1,150 ft",
    description: "An adventurous alternative to the Koko Head stairs. Follow the crater rim to the summit with views of Hawaii Kai, Hanauma Bay, and the east coast.",
    tags: ["Rim", "Summit", "Adventure", "Loop"],
    image: "/images/real/3_Koko_Crater_Railway_Trail_Oahu_A.jpg",
    imageIsReal: true,
    region: "Honolulu",
    tips: ["Less crowded than the stairs route", "Bring plenty of water — exposed trail", "Loop back via Koko Crater Botanical Gardens"],
    bestFor: ["Adventurers", "Crater views", "Botanical gardens"],
  },
  {
    id: "palI-notches",
    name: "Pali Notches",
    difficulty: "Hard",
    distance: "0.75 mi",
    duration: "1.5 hrs",
    elevation: "500 ft",
    description: "Dangerous ridge scramble to notches carved in the 1700s by King Kamehameha's warriors. One of the closest hikes to downtown Honolulu for sunset.",
    tags: ["Dangerous", "Ridge", "Historic", "Scramble"],
    image: "/images/real/2_Pali_Notches_A_Daring_Class_4_Scramble.jpg",
    imageIsReal: true,
    region: "Central",
    tips: ["One of the most dangerous hikes on Oahu — many falls", "Notches were carved to harbor cannons in the 1700s", "Trailhead at the Pali Lookout platform"],
    bestFor: ["Experienced hikers", "History buffs", "Thrill seekers"],
  },
  {
    id: "olomana-three-peaks",
    name: "Olomana (Three Peaks) Trail",
    difficulty: "Expert",
    distance: "5 mi",
    duration: "2-3 hrs",
    elevation: "1,970 ft",
    description: "Three dramatic peaks with steep drop-offs on all sides. The first peak is straightforward; peaks two and three bring out your fear of heights. Several deaths have occurred.",
    tags: ["Dangerous", "Ridge", "Multi-Peak", "Expert Only"],
    image: "/images/real/6_Olomana_Three_Peaks_Trail_All_You.jpg",
    imageIsReal: true,
    region: "Windward",
    tips: ["Don't be too proud to stop at the first peak — great views there", "Not much room for error — steep drop-offs", "Check weather — very dangerous when wet"],
    bestFor: ["Expert hikers", "Adrenaline junkies", "Ridge lovers"],
  },
  {
    id: "crouching-lion",
    name: "Crouching Lion Trail",
    difficulty: "Moderate",
    distance: "2 mi",
    duration: "1-2 hrs",
    elevation: "500 ft",
    description: "Short but steep hike with breathtaking views of Kahana Bay, Kaaawa, and the cliffs of Pu'u Manamana. One of the most beautiful hikes on Oahu.",
    tags: ["Viewpoint", "Short", "Photography", "Coastal"],
    image: "/images/real/2_Crouching_Lion_Trail_view_of_Kahana.jpg",
    imageIsReal: true,
    region: "Windward",
    tips: ["Trail is slippery due to dry crumbling dirt", "Several viewpoints along the way", "Very dangerous — take care on narrow sections"],
    bestFor: ["Photography lovers", "Short hike seekers", "Coastal views"],
  },
  {
    id: "hanauma-bay-ridge",
    name: "Hanauma Bay Ridge Hike",
    difficulty: "Moderate",
    distance: "3.5 mi",
    duration: "1-1.5 hrs",
    elevation: "500 ft",
    description: "The best way to see Hanauma Bay is from above. Short ridge hike with stunning views of the bay and Koko Head Crater as backdrop.",
    tags: ["Ridge", "Viewpoint", "Short"],
    image: "/images/real/8_Must_things_to_do_in_Honolulu_Conquer.jpg",
    imageIsReal: true,
    region: "Honolulu",
    tips: ["Start from Koko Head parking lot for the full route", "Best panoramic view of Hanauma Bay", "Combine with Koko Head Crater for a full day"],
    bestFor: ["Photographers", "Bay views", "Short hike"],
  },
  {
    id: "makiki-valley-loop",
    name: "Makiki Valley Loop Trail",
    difficulty: "Moderate",
    distance: "3.2 mi",
    duration: "2 hrs",
    elevation: "920 ft",
    description: "One of the most beautiful easy hikes near Waikiki. Walls of green, ferns reaching over the trail, natural tree arches, and the sound of running water.",
    tags: ["Forest", "Loop", "Near Waikiki", "Water"],
    image: "/images/real/10_Hiking_Manoa_Falls_Trail_In_Honolulu.jpg",
    imageIsReal: true,
    region: "Honolulu",
    tips: ["Just minutes from downtown Honolulu", "Multiple loop options available", "Trail can be muddy after rain"],
    bestFor: ["Nature lovers", "Quick escapes", "Forest bathing"],
  },
  {
    id: "judd-trail",
    name: "Judd Trail",
    difficulty: "Easy",
    distance: "1.2 mi",
    duration: "1 hr",
    elevation: "150 ft",
    description: "Natural water slides, rope swings, a bamboo forest, and Jackass Ginger Pool. One of the best off-the-beaten-path easy hikes on Oahu.",
    tags: ["Water Slide", "Bamboo", "Family", "Swimming"],
    image: "/images/real/9_Diamond_Head_L_ahi_for_visitors_everything.jpg",
    imageIsReal: true,
    region: "Central",
    tips: ["Don't go if raining — flash flood risk", "Trail starts across from the Pali Lookout", "Limited street parking — don't leave valuables"],
    bestFor: ["Families", "Swimming holes", "Bamboo forest"],
  },
  {
    id: "wailupe-loop",
    name: "Wailupe Loop Trail",
    difficulty: "Hard",
    distance: "5.2 mi",
    duration: "3-5 hrs",
    elevation: "2,624 ft",
    description: "Challenging loop with thick overgrowth, uneven terrain, and 800m of steep ascent on the Koolau Summit Trail. Connects to Wiliwilinui Ridge for descent.",
    tags: ["Loop", "KST", "Challenging", "Overgrown"],
    image: "/images/real/10_Wiliwilinui_Ridge_Trail_Oahu_s_Best.jpg",
    imageIsReal: true,
    region: "Central",
    tips: ["For experienced hikers only", "Very steep and muddy sections", "Links to Wiliwilinui Ridge Trail for descent"],
    bestFor: ["Experienced hikers", "KST explorers", "Challenge seekers"],
  },
  {
    id: "pride-rock",
    name: "Pride Rock to Pu'u Ohulehule",
    difficulty: "Expert",
    distance: "5.6 mi",
    duration: "5-7 hrs",
    elevation: "2,950 ft",
    description: "Pride Rock is a 30-minute sunrise viewpoint. Continuing to Pu'u Ohulehule is a technical, challenging route with 900m of elevation gain over narrow ridges.",
    tags: ["Sunrise", "Technical", "Ridge", "Expert Only"],
    image: "/images/real/10_Paradise_Cove_Beach_Photography_KoOlina.jpg",
    imageIsReal: true,
    region: "Windward",
    tips: ["Pride Rock alone is 30 min — great for all levels", "Pu'u Ohulehule is 5-7 hours — expert only", "Technical terrain with rope sections"],
    bestFor: ["Expert hikers", "Sunrise seekers", "Technical climbers"],
  },
  {
    id: "puu-piei",
    name: "Pu'u Piei Makai Trail",
    difficulty: "Hard",
    distance: "2.5 mi",
    duration: "3-4 hrs",
    elevation: "1,770 ft",
    description: "Steep climb with 500m of elevation over Kahana Bay. Rocky outcrops with ropes and scrambles. Adjacent to the popular Crouching Lion Hike.",
    tags: ["Steep", "Ropes", "Coastal View", "Challenge"],
    image: "/images/real/8_View_From_Crouching_Lion_Hike_Overlooking.jpg",
    imageIsReal: true,
    region: "Windward",
    tips: ["Much harder than Crouching Lion nearby", "Numerous rocky scrambles with ropes", "Incredible views over Kahana Bay"],
    bestFor: ["Experienced adventurers", "Ridge hikers", "Challenge seekers"],
  },
  {
    id: "nuuanu-trail",
    name: "Nuuanu Trail to Pali Lookout",
    difficulty: "Moderate",
    distance: "6.2 mi",
    duration: "3-4 hrs",
    elevation: "1,640 ft",
    description: "Starts on Judd Trail with stream crossings and bamboo forest. Climbs via switchbacks to the Pali Lookout before returning on the ridge.",
    tags: ["Loop", "Bamboo", "Stream", "Historic"],
    image: "/images/real/6_Lanikai_Pillbox_Hawaii_Travel_Guid.jpg",
    imageIsReal: true,
    region: "Central",
    tips: ["Mix of maintained trails and wild single-track", "Multiple stream crossings on Judd Trail", "Great views from the Pali Lookout"],
    bestFor: ["Loop hikers", "Bamboo forest", "History"],
  },
  {
    id: "puu-manamana",
    name: "Pu'u Manamana Trail",
    difficulty: "Expert",
    distance: "4 mi",
    duration: "3-4 hrs",
    elevation: "2,000 ft",
    description: "Challenging trail running above Crouching Lion on a narrow ridge with steep drop-offs on both sides. Rock scrambles, rope sections, and muddy slopes.",
    tags: ["Dangerous", "Ridge", "Narrow", "Ropes"],
    image: "/images/real/9_Pali_Notches_A_Daring_Class_4_Scramble.jpg",
    imageIsReal: true,
    region: "Windward",
    tips: ["Narrow ridge with steep drop-offs — not for beginners", "Rock scrambles and rope sections", "Incredible views of Kahana Bay"],
    bestFor: ["Expert hikers", "Thrill seekers", "Ridge walkers"],
  },
  {
    id: "manoa-cliff",
    name: "Manoa Cliff Trail",
    difficulty: "Easy-Moderate",
    distance: "4 mi",
    duration: "2-3 hrs",
    elevation: "900 ft",
    description: "Winds through lush tropical rainforest with the unique feature of 'bamboo hallways' — incredibly beautiful sections of dense bamboo.",
    tags: ["Bamboo", "Rainforest", "Cliff", "Morning"],
    image: "/images/real/2_Hiking_Manoa_Falls_Trail_In_Honolulu.jpg",
    imageIsReal: true,
    region: "Honolulu",
    tips: ["Best as a short morning hike", "Some inclines and narrow paths", "Connects to other Manoa trails"],
    bestFor: ["Nature lovers", "Bamboo enthusiasts", "Morning hikers"],
  },
  {
    id: "hauula-loop",
    name: "Hau'ula Loop Trail",
    difficulty: "Moderate",
    distance: "4.4 mi",
    duration: "2-3 hrs",
    elevation: "900 ft",
    description: "Peaceful forest trail through Ironwood and Cook Pines on Oahu's northeastern coast. Panoramic views of the coastline and Hau'ula Beach Park.",
    tags: ["Forest", "Loop", "Coastal View", "Peaceful"],
    image: "/images/real/4_Crouching_Lion_Trail_2026_All_You.jpg",
    imageIsReal: true,
    region: "Windward",
    tips: ["No real dangers or drop-offs", "Add Waipilopilo Loop for extra challenge", "Steady incline — decent fitness recommended"],
    bestFor: ["Forest bathers", "Loop hikers", "Coastal views"],
  },
  {
    id: "puu-pia",
    name: "Pu'u Pia Trail",
    difficulty: "Easy-Moderate",
    distance: "3.6 mi",
    duration: "2 hrs",
    elevation: "670 ft",
    description: "Easy-to-moderate hike through lush forest with picturesque views of the Ko'olau Mountain range. No steep drop-offs.",
    tags: ["Forest", "Ko'olau Views", "Family Friendly", "Peaceful"],
    image: "/images/real/1_Hawaii_Oahu_Lanikai_Beach_With_Calm.jpg",
    imageIsReal: true,
    region: "Central",
    tips: ["Suitable for all levels", "Steady incline workout", "Great Ko'olau mountain views"],
    bestFor: ["Families", "Beginners", "Mountain views"],
  },
  {
    id: "kaau-crater",
    name: "Ka'au Crater Trail",
    difficulty: "Hard",
    distance: "5 mi",
    duration: "4-5 hrs",
    elevation: "2,000 ft",
    description: "Challenging loop combining three waterfalls, ridgeline views, and walking around a crater rim. Muddy and strenuous with rope climbs.",
    tags: ["Waterfall", "Crater", "Ridgeline", "Ropes"],
    image: "/images/real/3_Hanauma_Bay_Reef_Map_Hanauma_Bay.jpg",
    imageIsReal: true,
    region: "Honolulu",
    tips: ["Start early — takes 4-5 hours", "Bring plenty of water and expect to get dirty", "Three waterfalls along the route"],
    bestFor: ["Experienced hikers", "Waterfall chasers", "Crater explorers"],
  },
  {
    id: "friendship-gardens",
    name: "Friendship Gardens Trail",
    difficulty: "Easy",
    distance: "0.7 mi",
    duration: "30-45 min",
    elevation: "200 ft",
    description: "Hidden gem in Kane'ohe with stunning views of the Ko'olau Mountains and Kane'ohe Bay. Native plants and shaded benches along the way.",
    tags: ["Easy", "Garden", "Viewpoint", "Short"],
    image: "/images/real/10_Hiking_Manoa_Falls_Trail_In_Honolulu.jpg",
    imageIsReal: true,
    region: "Windward",
    tips: ["Look for the small sign at the trailhead on Kokokahi Place", "Parking is limited in residential area", "Upper lookout has wide bay views"],
    bestFor: ["Families", "Quick hike", "Garden lovers"],
  },
  {
    id: "ualakaa",
    name: "Ualaka'a Trail",
    difficulty: "Easy",
    distance: "1 mi",
    duration: "30-45 min",
    elevation: "Minimal",
    description: "Shaded, peaceful forest loop at Pu'u Ualaka'a State Park with panoramic views of Diamond Head and Honolulu. Great for picnics and sunsets.",
    tags: ["Easy", "Loop", "Sunset", "Family"],
    image: "/images/real/2_Diamond_Head_L_ahi_for_visitors_everything.jpg",
    imageIsReal: true,
    region: "Honolulu",
    tips: ["Restrooms and picnic tables available", "Scenic overlook near parking lot", "Great for picnics and sunsets"],
    bestFor: ["Families", "Beginners", "Sunset views"],
  },
  {
    id: "lulumahu-falls",
    name: "Lulumahu Falls",
    difficulty: "Moderate",
    distance: "2-3 mi",
    duration: "1.5-2 hrs",
    elevation: "Minimal",
    description: "Government-regulated area requiring a $2.50 day-use permit. True jungle trek crossing streams, navigating giant roots, through a massive bamboo forest to a 50-foot waterfall.",
    tags: ["Waterfall", "Bamboo", "Jungle", "Permit Required"],
    image: "/images/real/10_Hiking_Manoa_Falls_Trail_In_Honolulu.jpg",
    imageIsReal: true,
    region: "Central",
    tips: ["Apply for permit on DLNR website before going", "Follow colored ribbons — easy to lose the trail", "Go in morning with plenty of daylight"],
    bestFor: ["Jungle trekkers", "Waterfall hunters", "Adventurers"],
  },
  {
    id: "laie-falls",
    name: "La'ie Falls Trail",
    difficulty: "Moderate-Hard",
    distance: "7 mi",
    duration: "4-5 hrs",
    elevation: "1,500 ft",
    description: "Long forest hike leading to a beautiful waterfall hidden deep in the jungle. Mix of forest, ridge views, wildflowers, and peaceful scenery.",
    tags: ["Waterfall", "Forest", "Wildflowers", "Long Hike"],
    image: "/images/real/1_Waimanalo_Beach_2026_All_You_SHOULD.jpg",
    imageIsReal: true,
    region: "Windward",
    tips: ["Start early — takes several hours", "Wear proper hiking shoes — muddy and uneven", "Beautiful wildflowers in season"],
    bestFor: ["Long-distance hikers", "Waterfall seekers", "Nature lovers"],
  },
  {
    id: "kealia-trail",
    name: "Kealia Trail",
    difficulty: "Moderate",
    distance: "6.5 mi",
    duration: "2-3 hrs",
    elevation: "1,500 ft",
    description: "Amazing mountain and coastal views via switchbacks. One of the best hikes for photographers on Oahu's central north side.",
    tags: ["Switchbacks", "Coastal View", "Photography", "Long"],
    image: "/images/real/1_Aerial_view_of_a_Kailua_beach_on.jpg",
    imageIsReal: true,
    region: "Central",
    tips: ["Begin early to avoid strong sun exposure", "Carry enough water — little shade", "Stunning ridge views at the top"],
    bestFor: ["Photographers", "Long hike lovers", "Coastal views"],
  },
  {
    id: "sunset-pillbox",
    name: "Sunset Pillbox Hike",
    difficulty: "Easy-Moderate",
    distance: "1.5 mi",
    duration: "1 hr",
    elevation: "400 ft",
    description: "Trail to colorful pillbox bunkers overlooking the ocean. Stunning sunset views over the North Shore. A local favorite.",
    tags: ["Sunset", "Pillbox", "North Shore", "Short"],
    image: "/images/real/8_Ehukai_Pillbox_Hike_The_Best_Hike.jpg",
    imageIsReal: true,
    region: "North Shore",
    tips: ["Arrive 30-45 minutes before sunset", "Carry a flashlight for the descent after dark", "Colorful painted bunkers at the top"],
    bestFor: ["Sunset chasers", "Photographers", "Short hike"],
  },
  {
    id: "kauna-trail",
    name: "Kaunala Trail",
    difficulty: "Hard",
    distance: "6 mi",
    duration: "3-4 hrs",
    elevation: "1,200 ft",
    description: "True hidden gem on the North Shore. Less crowded with deep forest sections, ridge walks, and quiet natural scenery. More adventurous.",
    tags: ["Hidden Gem", "Forest", "Ridge", "Quiet"],
    image: "/images/real/1_Hawaii_Oahu_Lanikai_Beach_With_Calm.jpg",
    imageIsReal: true,
    region: "North Shore",
    tips: ["Go early — trail is longer and more challenging", "Bring extra water", "Less trafficked than other North Shore trails"],
    bestFor: ["Solitude seekers", "Forest hikers", "Adventurers"],
  },
  {
    id: "puu-konahuanui",
    name: "Pu'u Konahuanui (K1, K2)",
    difficulty: "Expert",
    distance: "7.5 mi",
    duration: "4-5 hrs",
    elevation: "3,150 ft",
    description: "Very adventurous, muddy ascent to the two highest peaks in the Ko'olau Range. K2 is among the tallest mountains on Oahu at 3,150 ft. Wild and for experienced hikers.",
    tags: ["Expert", "Highest Peak", "Ko'olau", "Muddy"],
    image: "/images/real/10_Aiea_Loop_Trail_2026_All_You_SHOULD.jpg",
    imageIsReal: true,
    region: "Central",
    tips: ["For experienced hikers only — very wild trail", "Extremely muddy even in dry conditions", "Among the tallest peaks on Oahu"],
    bestFor: ["Peak baggers", "Expert hikers", "Ko'olau explorers"],
  },
];

// ─── All Beaches (27) ──────────────────────────────────

export const beaches: Beach[] = [
  {
    id: "waikiki",
    name: "Waikiki Beach",
    crowdLevel: 5,
    crowdLabel: "Very High",
    description: "The heart of Hawaii — calm water, surf lessons, outrigger canoeing, sunset views, and endless energy along a 2-mile stretch of white sand.",
    activities: ["Swimming", "Surfing", "Canoeing", "Sunset"],
    region: "Honolulu",
    image: "/images/real/6_Diamond_Head_Honolulu_s_Favourite.jpg",
    imageIsReal: true,
    facilities: [
      { name: "Restrooms", available: true },
      { name: "Showers", available: true },
      { name: "Lifeguards", available: true },
      { name: "Parking", available: true },
      { name: "Rentals", available: true },
    ],
    bestSeason: "Year-round",
    surf: { waveSize: "1-3 ft", skillLevel: "Beginner", bestMonths: "Year-round" },
    tips: ["Best for beginner surfing lessons", "Very crowded — arrive early", "Beautiful sunset views from the beach"],
  },
  {
    id: "lanikai",
    name: "Lanikai Beach",
    crowdLevel: 5,
    crowdLabel: "Very High",
    description: "Covered with fine white sand and calm turquoise water. Most rank this beach as one of the best in the world. Views of two offshore islands known as 'the Mokes.'",
    activities: ["Swimming", "Kayaking", "Snorkeling", "Sailing"],
    region: "Windward",
    image: "/images/real/5_Is_Lanikai_Beach_the_Best_Beach_on.jpg",
    imageIsReal: true,
    facilities: [
      { name: "Restrooms", available: false },
      { name: "Showers", available: false },
      { name: "Lifeguards", available: false },
      { name: "Parking", available: false },
      { name: "Rentals", available: false },
    ],
    bestSeason: "Year-round",
    surf: { waveSize: "0-2 ft", skillLevel: "Beginner", bestMonths: "Year-round" },
    tips: ["No facilities — bring everything you need", "Parking on residential streets — arrive by 7 AM", "Kayak to the Mokolua Islands for an adventure"],
  },
  {
    id: "kailua",
    name: "Kailua Beach Park",
    crowdLevel: 4,
    crowdLabel: "High",
    description: "2.5 miles of family-friendly shoreline with soft waves, lifeguards, picnic areas, and easy parking. A local favorite for kayaking and windsurfing.",
    activities: ["Swimming", "Kayaking", "Windsurfing", "Kiteboarding"],
    region: "Windward",
    image: "/images/real/1_Aerial_view_of_a_Kailua_beach_on.jpg",
    imageIsReal: true,
    facilities: [
      { name: "Restrooms", available: true },
      { name: "Showers", available: true },
      { name: "Lifeguards", available: true },
      { name: "Parking", available: true },
      { name: "Rentals", available: true },
    ],
    bestSeason: "Year-round",
    surf: { waveSize: "0-2 ft", skillLevel: "Beginner", bestMonths: "Year-round" },
    tips: ["Great for families — lifeguards on duty", "Rent kayaks in Kailua town", "Parking lot fills by 8:30 AM"],
  },
  {
    id: "hanauma-bay",
    name: "Hanauma Bay Nature Preserve",
    crowdLevel: 5,
    crowdLabel: "Very High",
    description: "A gorgeous wineglass-shaped bay with a shallow reef in a protected marine preserve. Thousands visit daily for some of the best snorkeling in Hawaii.",
    activities: ["Snorkeling", "Swimming", "Nature Education"],
    region: "Honolulu",
    image: "/images/real/4_Snorkeling_in_Hanauma_Bay_Things.jpg",
    imageIsReal: true,
    facilities: [
      { name: "Restrooms", available: true },
      { name: "Showers", available: true },
      { name: "Lifeguards", available: true },
      { name: "Parking", available: true },
      { name: "Rentals", available: true },
    ],
    bestSeason: "Year-round",
    surf: { waveSize: "Flat", skillLevel: "Beginner", bestMonths: "Year-round" },
    tips: ["$7.50 entry fee for non-residents", "Closed on Mondays and Tuesdays", "Mandatory safety video before entry"],
  },
  {
    id: "waimanalo",
    name: "Waimanalo Beach",
    crowdLevel: 2,
    crowdLabel: "Low",
    description: "Miles of quiet shoreline with powdery white sand, natural shade from ironwood trees, and stunning turquoise water. Once voted the #1 beach in America.",
    activities: ["Swimming", "Beach Walk", "Camping", "Fishing"],
    region: "Windward",
    image: "/images/real/4_Crouching_Lion_Trail_2026_All_You.jpg",
    imageIsReal: true,
    facilities: [
      { name: "Restrooms", available: true },
      { name: "Showers", available: false },
      { name: "Lifeguards", available: false },
      { name: "Parking", available: true },
      { name: "Rentals", available: false },
    ],
    bestSeason: "Year-round",
    tips: ["One of the quietest beaches on Oahu", "Natural shade from ironwood trees", "Bring supplies — shops are far away"],
  },
  {
    id: "sunset-beach",
    name: "Sunset Beach",
    crowdLevel: 4,
    crowdLabel: "High",
    description: "Legendary North Shore surf spot. Winter waves reach 15-20+ feet, attracting the world's best surfers. The Vans Triple Crown is held here each winter.",
    activities: ["Surfing", "Bodyboarding", "Sunset Watching"],
    region: "North Shore",
    image: "/images/real/7_Spot_Check_Sunset_Beach_T_C_Surf.jpg",
    imageIsReal: true,
    facilities: [
      { name: "Restrooms", available: true },
      { name: "Showers", available: true },
      { name: "Lifeguards", available: true },
      { name: "Parking", available: true },
      { name: "Rentals", available: false },
    ],
    bestSeason: "Winter for surf, Summer for swimming",
    surf: { waveSize: "10-20+ ft", skillLevel: "Expert", bestMonths: "Nov-Feb" },
    tips: ["Watch pro surfers in winter from shore", "Swimming only in summer when waves are calm", "Famous for golden sunset views"],
  },
  {
    id: "waimea-bay",
    name: "Waimea Bay",
    crowdLevel: 4,
    crowdLabel: "High",
    description: "One of the world's most famous big-wave surf sites. In summer, the bay becomes a peaceful swimming and cliff-jumping spot. Waves can top 40 feet in winter.",
    activities: ["Surfing", "Cliff Jumping", "Swimming", "Bodyboarding"],
    region: "North Shore",
    image: "/images/real/7_Waimea_Valley_Hike_Swim_Oahu_2026.jpg",
    imageIsReal: true,
    facilities: [
      { name: "Restrooms", available: true },
      { name: "Showers", available: true },
      { name: "Lifeguards", available: true },
      { name: "Parking", available: true },
      { name: "Rentals", available: false },
    ],
    bestSeason: "Summer for swimming, Winter for surf watching",
    surf: { waveSize: "15-40 ft", skillLevel: "Expert", bestMonths: "Nov-Feb" },
    tips: ["Cliff jumping popular in summer", "Extremely dangerous in winter — stay on shore", "The Eddie big wave competition held here"],
  },
  {
    id: "ehukai",
    name: "Ehukai Beach (Banzai Pipeline)",
    crowdLevel: 5,
    crowdLabel: "Very High",
    description: "Home to the world-famous Banzai Pipeline — one of the most dangerous and photographed waves on Earth. The Billabong Pipe Masters is held here each December.",
    activities: ["Surfing", "Bodyboarding", "Spectating"],
    region: "North Shore",
    image: "/images/real/7_Spot_Check_Sunset_Beach_T_C_Surf.jpg",
    imageIsReal: true,
    facilities: [
      { name: "Restrooms", available: true },
      { name: "Showers", available: true },
      { name: "Lifeguards", available: true },
      { name: "Parking", available: true },
      { name: "Rentals", available: false },
    ],
    bestSeason: "Winter for surf, Summer for snorkeling",
    surf: { waveSize: "8-20+ ft", skillLevel: "Expert", bestMonths: "Nov-Feb" },
    tips: ["Spectate from the beach in winter — don't enter water", "Flat in summer — good for snorkeling over reef", "Parking fills extremely early in winter"],
  },
  {
    id: "ala-moana",
    name: "Ala Moana Beach Park",
    crowdLevel: 3,
    crowdLabel: "Moderate",
    description: "A half-mile-long white sandy beach protected by a reef with usually calm, clear waters. Locals' favorite for paddling, yoga, running, and volleyball.",
    activities: ["Swimming", "Paddleboarding", "Jogging", "Volleyball"],
    region: "Honolulu",
    image: "/images/real/2_Ehukai_Pillbox_Hawaii_Travel_Guid.jpg",
    imageIsReal: true,
    facilities: [
      { name: "Restrooms", available: true },
      { name: "Showers", available: true },
      { name: "Lifeguards", available: true },
      { name: "Parking", available: true },
      { name: "Rentals", available: true },
    ],
    bestSeason: "Year-round",
    tips: ["Magic Island has a calm lagoon for kids", "Free parking lots (fill by mid-morning)", "Popular with locals for weekend picnics"],
  },
  {
    id: "ko-olina",
    name: "Ko Olina Lagoons",
    crowdLevel: 4,
    crowdLabel: "High",
    description: "Four calm man-made lagoons with pool-like water, lifeguards, restrooms, and resort amenities. The safest choice for families with young children.",
    activities: ["Swimming", "Snorkeling", "Sunset Walk"],
    region: "Leeward",
    image: "/images/real/beach-koolina.jpg",
    imageIsReal: true,
    facilities: [
      { name: "Restrooms", available: true },
      { name: "Showers", available: true },
      { name: "Lifeguards", available: true },
      { name: "Parking", available: true },
      { name: "Rentals", available: true },
    ],
    bestSeason: "Year-round",
    surf: { waveSize: "Flat", skillLevel: "Beginner", bestMonths: "Year-round" },
    tips: ["Parking fills by 9 AM — arrive early", "Pool-like calm water perfect for kids", "Walking path connects all four lagoons"],
  },
  {
    id: "sharks-cove",
    name: "Shark's Cove",
    crowdLevel: 3,
    crowdLabel: "Moderate",
    description: "A protected marine conservation district. During calm summer months, this is one of the best snorkeling spots on the North Shore with diverse marine life.",
    activities: ["Snorkeling", "Tide Pools", "Diving"],
    region: "North Shore",
    image: "/images/real/4_Wiliwilinui_Ridge_Trail_2026_All.jpg",
    imageIsReal: true,
    facilities: [
      { name: "Restrooms", available: true },
      { name: "Showers", available: false },
      { name: "Lifeguards", available: false },
      { name: "Parking", available: true },
      { name: "Rentals", available: false },
    ],
    bestSeason: "Summer only (May-Sept)",
    surf: { waveSize: "Flat-3 ft", skillLevel: "Beginner", bestMonths: "May-Sept" },
    tips: ["Summer only — dangerous in winter", "Wear reef shoes — rocky entry", "Food trucks nearby for lunch"],
  },
  {
    id: "laniakea",
    name: "Laniakea (Turtle Beach)",
    crowdLevel: 3,
    crowdLabel: "Moderate",
    description: "A gentle reef break popular with longboarders. Famous for Hawaiian green sea turtles resting on the beach. Great for beginner surfers when small.",
    activities: ["Swimming", "Surfing", "Turtle Watching"],
    region: "North Shore",
    image: "/images/real/6_Waimea_Bay_the_birthplace_of_big.jpg",
    imageIsReal: true,
    facilities: [
      { name: "Restrooms", available: false },
      { name: "Showers", available: false },
      { name: "Lifeguards", available: false },
      { name: "Parking", available: true },
      { name: "Rentals", available: false },
    ],
    bestSeason: "Year-round",
    surf: { waveSize: "1-4 ft", skillLevel: "Beginner", bestMonths: "Year-round" },
    tips: ["Sea turtles often rest on the beach — keep 10ft distance", "Watch for traffic when crossing Kamehameha Hwy", "Great for beginner longboarders"],
  },
  {
    id: "electric-beach",
    name: "Electric Beach (Kahe Point)",
    crowdLevel: 2,
    crowdLabel: "Low",
    description: "Named for the unique sensation of cool freshwater springs bubbling up through the reef. Warm water discharge attracts sea turtles, reef sharks, and diverse fish.",
    activities: ["Snorkeling", "Diving", "Wildlife"],
    region: "Leeward",
    image: "/images/real/3_Hawaiian_Monk_Seal_at_Kaena_Point.jpg",
    imageIsReal: true,
    facilities: [
      { name: "Restrooms", available: false },
      { name: "Showers", available: false },
      { name: "Lifeguards", available: false },
      { name: "Parking", available: true },
      { name: "Rentals", available: false },
    ],
    bestSeason: "Summer (May-Sept)",
    surf: { waveSize: "Flat-2 ft", skillLevel: "Intermediate", bestMonths: "May-Sept" },
    tips: ["No facilities — bring everything", "Limited parking — arrive 7-8 AM", "Strong currents possible — stay shallow"],
  },
  {
    id: "sandy-beach",
    name: "Sandy Beach",
    crowdLevel: 3,
    crowdLabel: "Moderate",
    description: "Known as one of the best bodysurfing beaches in the world — and one of the most dangerous. The shore break is powerful with strong currents.",
    activities: ["Bodyboarding", "Bodysurfing", "Spectating"],
    region: "Honolulu",
    image: "/images/real/9_Koko_Crater_Railway_Trail_Oahu_A.jpg",
    imageIsReal: true,
    facilities: [
      { name: "Restrooms", available: true },
      { name: "Showers", available: true },
      { name: "Lifeguards", available: true },
      { name: "Parking", available: true },
      { name: "Rentals", available: false },
    ],
    bestSeason: "Year-round",
    surf: { waveSize: "3-10 ft shorebreak", skillLevel: "Expert", bestMonths: "Year-round" },
    tips: ["Extremely dangerous shore break — experienced only", "Many spinal injuries occur here each year", "Great for watching experienced watermen"],
  },
  {
    id: "halona-cove",
    name: "Halona Beach Cove",
    crowdLevel: 2,
    crowdLabel: "Low",
    description: "Small cove tucked below the Halona Blowhole lookout. Featured in the movie 'From Here to Eternity.' Accessible via a steep, rocky scramble.",
    activities: ["Body Surfing", "Photography", "Exploring"],
    region: "Honolulu",
    image: "/images/real/8_Must_things_to_do_in_Honolulu_Conquer.jpg",
    imageIsReal: true,
    facilities: [
      { name: "Restrooms", available: false },
      { name: "Showers", available: false },
      { name: "Lifeguards", available: false },
      { name: "Parking", available: true },
      { name: "Rentals", available: false },
    ],
    bestSeason: "Summer",
    tips: ["Steep rocky scramble to access", "Also known as 'Eternity Beach'", "Check out the nearby Halona Blowhole"],
  },
  {
    id: "bellows",
    name: "Bellows Beach",
    crowdLevel: 2,
    crowdLabel: "Low",
    description: "Wide sandy beach popular with locals and military families. Gentle waves, ironwood trees for shade, and camping available on weekends.",
    activities: ["Swimming", "Camping", "Bodyboarding"],
    region: "Windward",
    image: "/images/real/1_Waimanalo_Beach_2026_All_You_SHOULD.jpg",
    imageIsReal: true,
    facilities: [
      { name: "Restrooms", available: true },
      { name: "Showers", available: true },
      { name: "Lifeguards", available: true },
      { name: "Parking", available: true },
      { name: "Rentals", available: false },
    ],
    bestSeason: "Year-round",
    tips: ["Weekend camping available with permit", "Gentle waves good for bodyboarding", "Open to public Fri-Sun only"],
  },
  {
    id: "chinamans-hat",
    name: "Chinaman's Hat (Mokolii)",
    crowdLevel: 2,
    crowdLabel: "Low",
    description: "A distinctive island in Kaneohe Bay shaped like a traditional Asian fishing hat. Kayak out and explore, or wade across at very low tide.",
    activities: ["Kayaking", "Exploring", "Photography"],
    region: "Windward",
    image: "/images/real/1_Hawaii_Oahu_Lanikai_Beach_With_Calm.jpg",
    imageIsReal: true,
    facilities: [
      { name: "Restrooms", available: true },
      { name: "Showers", available: false },
      { name: "Lifeguards", available: false },
      { name: "Parking", available: true },
      { name: "Rentals", available: false },
    ],
    bestSeason: "Summer (calm water)",
    tips: ["Kayak from Kualoa Regional Park", "Can wade across at very low tide", "Bring reef shoes for the rocky island"],
  },
  {
    id: "makapuu",
    name: "Makapuu Beach Park",
    crowdLevel: 3,
    crowdLabel: "Moderate",
    description: "Sheer black cliffs of the Ko'olau Volcano encircle this beautiful beach. Bodyboarders and surfers enjoy the rip currents and powerful shore break.",
    activities: ["Bodyboarding", "Surfing", "Hiking Nearby"],
    region: "Windward",
    image: "/images/real/1_Hiking_the_Makapuu_Lighthouse_Trai.jpg",
    imageIsReal: true,
    facilities: [
      { name: "Restrooms", available: true },
      { name: "Showers", available: true },
      { name: "Lifeguards", available: true },
      { name: "Parking", available: true },
      { name: "Rentals", available: false },
    ],
    bestSeason: "Summer for swimming",
    surf: { waveSize: "3-8 ft", skillLevel: "Intermediate", bestMonths: "Year-round" },
    tips: ["Bodyboarding beach — strong shore break", "Makapuu Lighthouse Trail starts nearby", "Amenities include picnic areas and BBQ grills"],
  },
  {
    id: "kahana-bay",
    name: "Kahana Bay Beach Park",
    crowdLevel: 1,
    crowdLabel: "Low",
    description: "Nestled on the upper windward side with tall cliffs and a large bay. Seldom more than a handful of people on weekdays. Popular for camping.",
    activities: ["Swimming", "Kayaking", "Camping", "Fishing"],
    region: "Windward",
    image: "/images/real/2_Crouching_Lion_Trail_view_of_Kahana.jpg",
    imageIsReal: true,
    facilities: [
      { name: "Restrooms", available: true },
      { name: "Showers", available: true },
      { name: "Lifeguards", available: false },
      { name: "Parking", available: true },
      { name: "Rentals", available: false },
    ],
    bestSeason: "Year-round",
    tips: ["Great camping spot with cabins available", "Crouching Lion trail is across the bay", "Weekdays are nearly empty"],
  },
  {
    id: "malaekahana",
    name: "Malaekahana Beach",
    crowdLevel: 1,
    crowdLabel: "Low",
    description: "A gem between La'ie and Kahuku. Local visitors come for camping, fishing, and plantation-style cabins. Excellent swimming with reef shoes.",
    activities: ["Swimming", "Camping", "Fishing"],
    region: "North Shore",
    image: "/images/real/5_Lanikai_Beach_Hills_Above_Kailua.jpg",
    imageIsReal: true,
    facilities: [
      { name: "Restrooms", available: true },
      { name: "Showers", available: true },
      { name: "Lifeguards", available: false },
      { name: "Parking", available: true },
      { name: "Rentals", available: false },
    ],
    bestSeason: "Summer",
    tips: ["Camping spots and plantation-style cabins available", "Wear reef shoes — rocky nearshore waters", "Boat ride to Goat Island offshore"],
  },
  {
    id: "yokohama",
    name: "Yokohama Bay (Keawa'ula)",
    crowdLevel: 1,
    crowdLabel: "Very Low",
    description: "The last beach before Kaena Point on the remote West Side. Pristine, untouched, and often empty. Stunning mountain backdrop and clear water.",
    activities: ["Swimming", "Beach Walk", "Fishing"],
    region: "Leeward",
    image: "/images/real/1_Hawaii_Oahu_Lanikai_Beach_With_Calm.jpg",
    imageIsReal: true,
    facilities: [
      { name: "Restrooms", available: false },
      { name: "Showers", available: false },
      { name: "Lifeguards", available: false },
      { name: "Parking", available: true },
      { name: "Rentals", available: false },
    ],
    bestSeason: "Summer",
    tips: ["Remote — bring all supplies", "Often completely empty on weekdays", "Combine with Kaena Point hike"],
  },
  {
    id: "pokai-bay",
    name: "Pokai Bay",
    crowdLevel: 2,
    crowdLabel: "Low",
    description: "A protected bay on the West Side with small, gentle waves. One of the safest swimming spots on the Leeward coast. Popular with locals.",
    activities: ["Swimming", "Picnicking", "Fishing"],
    region: "Leeward",
    image: "/images/real/10_Paradise_Cove_Beach_Photography_KoOlina.jpg",
    imageIsReal: true,
    facilities: [
      { name: "Restrooms", available: true },
      { name: "Showers", available: true },
      { name: "Lifeguards", available: true },
      { name: "Parking", available: true },
      { name: "Rentals", available: false },
    ],
    bestSeason: "Year-round",
    surf: { waveSize: "1-2 ft", skillLevel: "Beginner", bestMonths: "Year-round" },
    tips: ["Very calm water — great for kids", "Local beach park atmosphere", "Less crowded than tourist beaches"],
  },
  {
    id: "turtle-bay",
    name: "Turtle Bay",
    crowdLevel: 3,
    crowdLabel: "Moderate",
    description: "Home to the luxurious Turtle Bay Resort. Calm swimming when waves are flat, light snorkeling, and several nearby hiking trails.",
    activities: ["Swimming", "Snorkeling", "Hiking Nearby"],
    region: "North Shore",
    image: "/images/real/7_Waimea_Valley_Hike_Swim_Oahu_2026.jpg",
    imageIsReal: true,
    facilities: [
      { name: "Restrooms", available: true },
      { name: "Showers", available: true },
      { name: "Lifeguards", available: false },
      { name: "Parking", available: true },
      { name: "Rentals", available: true },
    ],
    bestSeason: "Year-round",
    tips: ["Free public parking near the resort", "Several hiking trails nearby", "Resort restaurants available"],
  },
  {
    id: "maili",
    name: "Maili Beach Park",
    crowdLevel: 2,
    crowdLabel: "Low",
    description: "Local beach park on the West Side with swimming, picnicking, and the Pink Pillbox hike visible on the ridge above.",
    activities: ["Swimming", "Picnicking", "Surfing"],
    region: "Leeward",
    image: "/images/real/3_Hiking_the_Pu_u_O_Hulu_Trail_Pink.jpg",
    imageIsReal: true,
    facilities: [
      { name: "Restrooms", available: true },
      { name: "Showers", available: true },
      { name: "Lifeguards", available: true },
      { name: "Parking", available: true },
      { name: "Rentals", available: false },
    ],
    bestSeason: "Year-round",
    tips: ["Local beach with fewer tourists", "Pink Pillbox hike starts nearby", "Good for a quiet beach day"],
  },
  {
    id: "nanakuli",
    name: "Nanakuli Beach Park",
    crowdLevel: 1,
    crowdLabel: "Low",
    description: "Quiet beach on the West Side with fewer crowds and warm waters. A local favorite for family gatherings and relaxed beach days.",
    activities: ["Swimming", "Picnicking", "Fishing"],
    region: "Leeward",
    image: "/images/real/10_Paradise_Cove_Beach_Photography_KoOlina.jpg",
    imageIsReal: true,
    facilities: [
      { name: "Restrooms", available: true },
      { name: "Showers", available: true },
      { name: "Lifeguards", available: true },
      { name: "Parking", available: true },
      { name: "Rentals", available: false },
    ],
    bestSeason: "Year-round",
    tips: ["Quiet local beach", "Warm, calm waters", "Good for a relaxed beach day away from crowds"],
  },
];

// ─── Surf Spots ────────────────────────────────────────

export const summerSurfSpots: SurfSpot[] = [
  { id: "waikiki-s", name: "Waikiki (Canoes)", waveHeight: 2, waveLabel: "1-3ft", skillLevel: "Beginner", description: "Gentle rolling waves perfect for first-time surfers. Longboard-friendly.", bestSeason: "Year-round", season: "year-round" },
  { id: "diamond-s", name: "Diamond Head Cliffs", waveHeight: 3, waveLabel: "2-4ft", skillLevel: "Intermediate", description: "Multiple reef breaks below the crater. Popular with local surfers.", bestSeason: "Summer", season: "summer" },
  { id: "ala-moana-s", name: "Ala Moana Bowls", waveHeight: 5, waveLabel: "3-6ft", skillLevel: "Intermediate-Expert", description: "Powerful left-hand reef. One of the best waves on the South Shore.", bestSeason: "Summer", season: "summer" },
  { id: "kewalos-s", name: "Kewalos", waveHeight: 4, waveLabel: "3-5ft", skillLevel: "Intermediate", description: "Fast right-hand reef break. Local crowd.", bestSeason: "Summer", season: "summer" },
  { id: "laniakea-s", name: "Laniakea", waveHeight: 2, waveLabel: "1-3ft", skillLevel: "Beginner", description: "Gentle reef break with sea turtles on the beach.", bestSeason: "Year-round", season: "year-round" },
  { id: "chuns-s", name: "Chun's Reef", waveHeight: 3, waveLabel: "2-4ft", skillLevel: "Intermediate", description: "Left and right waves. Popular with longboarders. Less crowded.", bestSeason: "Summer", season: "summer" },
  { id: "pokai-s", name: "Pokai Bay", waveHeight: 1.5, waveLabel: "1-2ft", skillLevel: "Beginner", description: "Protected bay on the West Side. Small, gentle waves.", bestSeason: "Year-round", season: "year-round" },
  { id: "kailua-s", name: "Kailua Beach", waveHeight: 1, waveLabel: "0-2ft", skillLevel: "Beginner", description: "Tiny trade-wind swells. Good for beginner longboarding.", bestSeason: "Year-round", season: "year-round" },
];

export const winterSurfSpots: SurfSpot[] = [
  { id: "pipeline-w", name: "Banzai Pipeline", waveHeight: 15, waveLabel: "8-20ft+", skillLevel: "Expert", description: "World-famous barreling reef break. Most dangerous and photographed wave. Hosts Pipe Masters.", bestSeason: "Winter", season: "winter" },
  { id: "sunset-w", name: "Sunset Beach", waveHeight: 15, waveLabel: "10-20ft+", skillLevel: "Expert", description: "Long powerful right-hand point break. Vans Triple Crown venue.", bestSeason: "Winter", season: "winter" },
  { id: "waimea-w", name: "Waimea Bay", waveHeight: 30, waveLabel: "15-50ft", skillLevel: "Expert", description: "Birthplace of big-wave surfing. The Eddie runs only in massive conditions.", bestSeason: "Winter", season: "winter" },
  { id: "haleiwa-w", name: "Haleiwa", waveHeight: 6, waveLabel: "4-8ft", skillLevel: "Intermediate", description: "Manageable right-hand reef. Good stepping stone to bigger breaks.", bestSeason: "Winter", season: "winter" },
  { id: "rocky-w", name: "Rocky Point", waveHeight: 9, waveLabel: "6-12ft", skillLevel: "Expert", description: "Fast hollow reef between Pipeline and Sunset.", bestSeason: "Winter", season: "winter" },
  { id: "velzy-w", name: "Velzyland", waveHeight: 6, waveLabel: "4-8ft", skillLevel: "Intermediate", description: "Right-hand reef. Less crowded North Shore option.", bestSeason: "Winter", season: "winter" },
  { id: "makaha-w", name: "Makaha", waveHeight: 10, waveLabel: "4-15ft", skillLevel: "Expert", description: "West Side point break. Local spot that holds big swells.", bestSeason: "Winter", season: "winter" },
  { id: "waikiki-w", name: "Waikiki", waveHeight: 3, waveLabel: "2-4ft", skillLevel: "Beginner", description: "South Shore still has small waves even in winter. Perfect for beginners.", bestSeason: "Year-round", season: "year-round" },
];

// ─── Map Locations ─────────────────────────────────────

export interface MapLocation {
  name: string;
  lat: number;
  lng: number;
  type: "trail" | "beach";
  difficulty?: string;
  crowdLevel?: number;
}

export const mapLocations: MapLocation[] = [
  // Trails
  { name: "Diamond Head Summit", lat: 21.2599, lng: -157.8057, type: "trail", difficulty: "Moderate" },
  { name: "Lanikai Pillbox", lat: 21.3783, lng: -157.7184, type: "trail", difficulty: "Easy-Moderate" },
  { name: "Koko Head Crater", lat: 21.2829, lng: -157.7058, type: "trail", difficulty: "Hard" },
  { name: "Manoa Falls", lat: 21.3330, lng: -157.8023, type: "trail", difficulty: "Easy" },
  { name: "Makapuu Lighthouse", lat: 21.3106, lng: -157.6498, type: "trail", difficulty: "Easy" },
  { name: "Ehukai Pillbox", lat: 21.5934, lng: -158.1035, type: "trail", difficulty: "Moderate" },
  { name: "Kaena Point", lat: 21.5790, lng: -158.2600, type: "trail", difficulty: "Easy-Moderate" },
  { name: "Waimea Valley", lat: 21.6383, lng: -158.0544, type: "trail", difficulty: "Easy" },
  { name: "Wiliwilinui Ridge", lat: 21.3155, lng: -157.7801, type: "trail", difficulty: "Moderate-Hard" },
  { name: "Kuliouou Ridge", lat: 21.3055, lng: -157.7314, type: "trail", difficulty: "Moderate" },
  { name: "Pink Pillbox", lat: 21.3936, lng: -158.1525, type: "trail", difficulty: "Moderate" },
  { name: "Aiea Loop", lat: 21.3847, lng: -157.9275, type: "trail", difficulty: "Moderate" },
  { name: "Olomana Three Peaks", lat: 21.3420, lng: -157.7150, type: "trail", difficulty: "Expert" },
  { name: "Crouching Lion", lat: 21.5565, lng: -157.8730, type: "trail", difficulty: "Moderate" },
  { name: "Pali Notches", lat: 21.3667, lng: -157.7917, type: "trail", difficulty: "Hard" },
  { name: "Makiki Valley Loop", lat: 21.3167, lng: -157.8167, type: "trail", difficulty: "Moderate" },
  { name: "Ka'au Crater", lat: 21.3167, lng: -157.7833, type: "trail", difficulty: "Hard" },
  { name: "Judd Trail", lat: 21.3500, lng: -157.8000, type: "trail", difficulty: "Easy" },
  { name: "Lulumahu Falls", lat: 21.3333, lng: -157.8000, type: "trail", difficulty: "Moderate" },
  { name: "Hau'ula Loop", lat: 21.6083, lng: -157.9167, type: "trail", difficulty: "Moderate" },
  { name: "Kealia Trail", lat: 21.5167, lng: -158.0167, type: "trail", difficulty: "Moderate" },
  { name: "La'ie Falls", lat: 21.6500, lng: -157.9167, type: "trail", difficulty: "Moderate-Hard" },
  { name: "Pride Rock", lat: 21.5333, lng: -157.8500, type: "trail", difficulty: "Hard" },
  { name: "Manoa Cliff Trail", lat: 21.3333, lng: -157.8000, type: "trail", difficulty: "Easy-Moderate" },
  { name: "Pu'u Pia Trail", lat: 21.3333, lng: -157.8000, type: "trail", difficulty: "Easy-Moderate" },
  { name: "Wailupe Loop", lat: 21.2833, lng: -157.7500, type: "trail", difficulty: "Hard" },
  { name: "Nuuanu Trail", lat: 21.3500, lng: -157.8000, type: "trail", difficulty: "Moderate" },
  { name: "Friendship Gardens", lat: 21.4167, lng: -157.8000, type: "trail", difficulty: "Easy" },
  { name: "Ualaka'a Trail", lat: 21.3167, lng: -157.8333, type: "trail", difficulty: "Easy" },
  { name: "Koko Crater Rim", lat: 21.2833, lng: -157.7000, type: "trail", difficulty: "Hard" },
  { name: "Hanauma Bay Ridge", lat: 21.2700, lng: -157.6960, type: "trail", difficulty: "Moderate" },
  { name: "Sunset Pillbox", lat: 21.6000, lng: -158.1000, type: "trail", difficulty: "Easy-Moderate" },
  { name: "Pu'u Manamana", lat: 21.5565, lng: -157.8730, type: "trail", difficulty: "Expert" },
  { name: "Kaunala Trail", lat: 21.6167, lng: -158.0833, type: "trail", difficulty: "Hard" },
  { name: "Pu'u Konahuanui", lat: 21.3667, lng: -157.8000, type: "trail", difficulty: "Expert" },
  // Beaches
  { name: "Waikiki Beach", lat: 21.2793, lng: -157.8292, type: "beach", crowdLevel: 5 },
  { name: "Lanikai Beach", lat: 21.3924, lng: -157.7188, type: "beach", crowdLevel: 5 },
  { name: "Kailua Beach", lat: 21.3973, lng: -157.7286, type: "beach", crowdLevel: 4 },
  { name: "Waimanalo Beach", lat: 21.3358, lng: -157.7006, type: "beach", crowdLevel: 2 },
  { name: "Hanauma Bay", lat: 21.2690, lng: -157.6938, type: "beach", crowdLevel: 5 },
  { name: "Sunset Beach", lat: 21.6800, lng: -158.0350, type: "beach", crowdLevel: 4 },
  { name: "Waimea Bay", lat: 21.6424, lng: -158.0634, type: "beach", crowdLevel: 4 },
  { name: "Ehukai Beach (Pipeline)", lat: 21.6654, lng: -158.0544, type: "beach", crowdLevel: 5 },
  { name: "Ala Moana Beach", lat: 21.2900, lng: -157.8500, type: "beach", crowdLevel: 3 },
  { name: "Ko Olina Lagoons", lat: 21.3400, lng: -158.1250, type: "beach", crowdLevel: 4 },
  { name: "Shark's Cove", lat: 21.6590, lng: -158.0610, type: "beach", crowdLevel: 3 },
  { name: "Laniakea Beach", lat: 21.6130, lng: -158.0860, type: "beach", crowdLevel: 3 },
  { name: "Makapuu Beach", lat: 21.3110, lng: -157.6580, type: "beach", crowdLevel: 3 },
  { name: "Sandy Beach", lat: 21.3250, lng: -157.6800, type: "beach", crowdLevel: 3 },
  { name: "Bellows Beach", lat: 21.3600, lng: -157.7100, type: "beach", crowdLevel: 2 },
  { name: "Kahana Bay", lat: 21.5560, lng: -157.8750, type: "beach", crowdLevel: 1 },
  { name: "Malaekahana Beach", lat: 21.6830, lng: -157.9330, type: "beach", crowdLevel: 1 },
  { name: "Turtle Bay", lat: 21.7000, lng: -157.9980, type: "beach", crowdLevel: 3 },
  { name: "Yokohama Bay", lat: 21.5750, lng: -158.2400, type: "beach", crowdLevel: 1 },
  { name: "Pokai Bay", lat: 21.4500, lng: -158.2000, type: "beach", crowdLevel: 2 },
  { name: "Electric Beach", lat: 21.3600, lng: -158.2100, type: "beach", crowdLevel: 2 },
  { name: "Halona Cove", lat: 21.2550, lng: -157.6850, type: "beach", crowdLevel: 2 },
  { name: "Chinaman's Hat", lat: 21.5100, lng: -157.8300, type: "beach", crowdLevel: 2 },
  { name: "Maili Beach", lat: 21.4000, lng: -158.1800, type: "beach", crowdLevel: 2 },
  { name: "Nanakuli Beach", lat: 21.3900, lng: -158.1600, type: "beach", crowdLevel: 1 },
];
